# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Главная
    url: /#top
    weight: 10
  - name: Features
    url: /#features
    weight: 20
  - name: Решения
    url: /#solutions
    weight: 30
  - name: Ресурсы
    weight: 40
    hasChildren: true
  - parent: Resources
    name: О нас
    url: blog/
